name: Restart Azure Container App

on:
  workflow_dispatch:
    inputs:
      container_app_name:
        description: 'Name of the Azure Container App to restart'
        required: true
      unique_id:
        description: 'Unique identifier for tracking this workflow run'
        required: true

jobs:
  restart-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Result JSON
        run: |
          mkdir -p output
          cat > output/result_${{ inputs.unique_id }}.json << 'EOF'
          {
            "run_id": "${{ github.run_id }}",
            "status": "running",
            "container_app_name": "${{ inputs.container_app_name }}",
            "unique_id": "${{ inputs.unique_id }}",
            "operation": "restart",
            "resource_group": "${{ secrets.AZURE_RESOURCE_GROUP }}",
            "restarted_at": null,
            "revision_name": null,
            "error": null,
            "message": "Starting container app restart process"
          }
          EOF

      - name: Restart Container App
        run: |
          set +e
          APP_NAME="${{ inputs.container_app_name }}"
          RESOURCE_GROUP="${{ secrets.AZURE_RESOURCE_GROUP }}"
          UNIQUE_ID="${{ inputs.unique_id }}"
          
          echo "Restarting Azure Container App: $APP_NAME in resource group: $RESOURCE_GROUP"
          
          # Create a new revision to restart the container app
          restart_output=$(az containerapp update \
            --name "$APP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --revision-suffix "restart-$(date +%s)" 2>&1)
          
          EXIT_CODE=$?
          
          if [ $EXIT_CODE -eq 0 ]; then
            echo "Container app restarted successfully"
            
            # Get the latest revision name
            revision_name=$(az containerapp revision list \
              --name "$APP_NAME" \
              --resource-group "$RESOURCE_GROUP" \
              --query "[0].name" \
              -o tsv 2>/dev/null || echo "unknown")
            
            cat > output/result_$UNIQUE_ID.json << EOF
          {
            "run_id": "${{ github.run_id }}",
            "status": "success",
            "container_app_name": "$APP_NAME",
            "unique_id": "$UNIQUE_ID",
            "operation": "restart",
            "resource_group": "$RESOURCE_GROUP",
            "restarted_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "revision_name": "$revision_name",
            "error": null,
            "message": "Container app '$APP_NAME' has been successfully restarted with new revision"
          }
          EOF
          else
            echo "Failed to restart container app: $restart_output"
            
            cat > output/result_$UNIQUE_ID.json << EOF
          {
            "run_id": "${{ github.run_id }}",
            "status": "failed",
            "container_app_name": "$APP_NAME",
            "unique_id": "$UNIQUE_ID",
            "operation": "restart",
            "resource_group": "$RESOURCE_GROUP",
            "restarted_at": null,
            "revision_name": null,
            "error": "Failed to restart container app",
            "message": "Restart failed: $restart_output"
          }
          EOF
          fi

      - name: Display Results
        if: always()
        run: |
          echo "=== Restart Result ==="
          if [ -f output/result_${{ inputs.unique_id }}.json ]; then
            cat output/result_${{ inputs.unique_id }}.json | jq . || cat output/result_${{ inputs.unique_id }}.json
          fi

      - name: Upload result artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: "result_${{ inputs.unique_id }}"
          path: "output/result_${{ inputs.unique_id }}.json"
